name: Deploy to HestiaCP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync files to server
      uses: easingthemes/ssh-deploy@v2.0.7
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "public_html/"
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        TARGET: ${{ secrets.TARGET }}
